### ISSUE TITLE
Stuck at Splash screen

### ISSUE THREAD

**Issue by clehner** [spruceid/credible#103]
The app hands at the splash screen (blurry view of the app). In the log, below, there is a "Unhandled Exception: PlatformException".

- Flutter (Channel main, 3.1.0-0.0.pre.1066, on Debian GNU/Linux bookworm/sid 5.15.0-3-amd64, locale C.UTF-8)
- Android SDK version 30.0.3
- Android version 11 (Linux 3.4.113-lineageos-ge89434a69fe), armv7l

```
$ flutter run
"fr": 5 untranslated message(s).
To see a detailed report, use the untranslated-messages-file
option in the l10n.yaml file:
untranslated-messages-file: desiredFileName.txt
<other option>: <other selection>


This will generate a JSON format file containing all messages that
need to be translated.
Launching lib/main.dart on SM G900T in debug mode...
Warning: The plugin qr_code_scanner requires Android SDK version 32.
For more information about build configuration, see https://docs.flutter.dev/deployment/android#reviewing-the-build-configuration.
One or more plugins require a higher Android SDK version.
Fix this issue by adding the following to /home/cel/src/credible/android/app/build.gradle:
android {
  compileSdkVersion 32
  ...
}

Running Gradle task 'assembleDebug'...                           2,691ms
✓  Built build/app/outputs/flutter-apk/app-debug.apk.
W/FlutterActivityAndFragmentDelegate( 4875): A splash screen was provided to Flutter, but this is deprecated. See flutter.dev/go/android-splash-migration for migration steps.
Syncing files to device SM G900T...                                137ms

Flutter run key commands.
r Hot reload. 🔥🔥🔥
R Hot restart.
h List all available interactive commands.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).

💪 Running with sound null safety 💪

An Observatory debugger and profiler on SM G900T is available at: http://127.0.0.1:41695/06rfaqJ1gng=/
I/flutter ( 4875): AppModule started!
I/flutter ( 4875): 0.4.0
The Flutter DevTools debugger and profiler on SM G900T is available at: http://127.0.0.1:9100?uri=http://127.0.0.1:41695/06rfaqJ1gng=/
E/flutter ( 4875): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(NotAvailable, Required security features not enabled, null, null)
E/flutter ( 4875): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:647:7)
E/flutter ( 4875): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:294:18)
E/flutter ( 4875): <asynchronous suspension>
E/flutter ( 4875): #2      LocalAuthentication.authenticate (package:local_auth/local_auth.dart:124:13)
E/flutter ( 4875): <asynchronous suspension>
E/flutter ( 4875): #3      _AppWidgetState._authenticate (package:credible/app/app_widget.dart:48:12)
E/flutter ( 4875): <asynchronous suspension>
E/flutter ( 4875): #4      _AppWidgetState._unlockOnLoad (package:credible/app/app_widget.dart:57:9)
E/flutter ( 4875): <asynchronous suspension>
E/flutter ( 4875):
I/flutter ( 4875): -- OnBoardingModule INITIALIZED
W/Adreno-EGL( 4875): <qeglDrvAPI_eglGetConfigAttrib:607>: EGL_BAD_ATTRIBUTE
W/Adreno-EGL( 4875): <qeglDrvAPI_eglGetConfigAttrib:607>: EGL_BAD_ATTRIBUTE
```

**Comment by clehner** [comment]
Workaround:
```diff
diff --git a/lib/app/app_widget.dart b/lib/app/app_widget.dart
index 47625c1..4092c19 100644
--- a/lib/app/app_widget.dart
+++ b/lib/app/app_widget.dart
@@ -43,13 +43,7 @@ class _AppWidgetState extends State<AppWidget> {
   }
 
   Future<bool> _authenticate() async {
-    final auth = LocalAuthentication();
-
-    return await auth.authenticate(
-      localizedReason: 'Please authenticate to use Credible',
-      useErrorDialogs: true,
-      stickyAuth: true,
-    );
+    return true;
   }
 
   Future<void> _unlockOnLoad() async {
```
